import "./globals.css";
import { STIX_Two_Text } from "next/font/google";
import AuthWrapper from "./AuthWrapper";

const font = STIX_Two_Text({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-[#E6DBD7] h-screen text-sm ${font.className}`}>
        <AuthWrapper>{children}</AuthWrapper>
      </body>
    </html>
  );
}
